### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by dlargen33** [hmhv/YoutubePlayer-in-WKWebView#16]
When I try to bring in the framework using SPM I am getting this error 
"https://github.com/hmhv/YoutubePlayer-in-WKWebView has no Package.swift manifest for version 0.3.5"  However if I point to master it comes in just fine.    

I have tried to specify lower versions, same error.

**Comment by hmhv** [comment]
Thank you for your trying. 
I made a tag 0.3.6. can you check this new tag?
