### ISSUE TITLE
Inconsistent player controls

### ISSUE THREAD

**Issue by nassifbasheer** [hmhv/YoutubePlayer-in-WKWebView#17]
Hi,

I am using the following params to load the youtube video 
`        let playerVars:[String: Any] = [
            "autoplay": "0","cc_load_policy":"0",
            "rel": "0",
            "playsinline" : "0",
            "showinfo":"1",
            "controls":"1", "modestbranding" : "1","iv_load_policy":"3","fs":1
        ]`

`mediaplayer?.load(withVideoId: videoID, playerVars: playerVars)`

how ever the controls are shown inconsistently. Please refer to the attached screenshots, the first image is the required and the second is the error controls obtained. Controls are working fine in emulator , but goes inconsistent in real device.

![Expected](https://user-images.githubusercontent.com/5028245/125218513-c32d2700-e2e0-11eb-8564-f24a3d24ee0f.png)

![Error](https://user-images.githubusercontent.com/5028245/125218540-d7712400-e2e0-11eb-9662-e954bd9e9da2.png)

**Comment by hmhv** [comment]
I'm not sure, but i think that's because of difference between screen size.
and you can't control that menu.

<img width="810" alt="スクリーンショット 2021-07-12 17 43 09" src="https://user-images.githubusercontent.com/10627645/125257693-a1f82500-e338-11eb-874f-103ee8c9e3d1.png">

**Comment by nassifbasheer** [comment]
Hi,

This happens in devices with same screen size as well..
