### ISSUE TITLE
SPM Support 

### ISSUE THREAD

**Issue by MercurialKZ** [hmhv/YoutubePlayer-in-WKWebView#21]
👋🏾, need spm support

**Comment by hmhv** [comment]
try again 👋🏾
<img width="830" alt="スクリーンショット 2021-10-09 9 44 35" src="https://user-images.githubusercontent.com/10627645/136637771-fce00dec-7b22-46b1-bbaa-3fab1a4991be.png">

**Comment by MercurialKZ** [comment]
thanks
