### ISSUE TITLE
Set up the volume of the player

### ISSUE THREAD

**Issue by youknowbaron** [hmhv/YoutubePlayer-in-WKWebView#25]
Hi everyone, 

I have a problem with setting up the volume of the player. I am using this. But it isn't working.
`videoView.webView?.evaluateJavaScript("player.setVolume(\(volume));"`
Is there anyway to set up the volume?

Thanks!

**Comment by hmhv** [comment]
You can't control volume of webview.

> On iOS devices, the audio level is always under the user’s physical control. The volume property is not settable in JavaScript. Reading the volume property always returns 1.

https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

**Comment by youknowbaron** [comment]
Oh, I see. Thank you for your response.
