### ISSUE TITLE
App Store Connect Operation Error

### ISSUE THREAD

**Issue by GustavoAlvarez** [hmhv/YoutubePlayer-in-WKWebView#30]
I'm getting this error when trying to upload to the app store, yesterday everything was fine, and today I got this message:

**App Store Connect Operation Error**

The app references non-public selectors in Payload/MyApp.app/Frameworks/YoutubePlayer_in_WKWebView.framework/YoutubePlayer_in_WKWebView: initWithFrame:configuration:, isMainFrame, setNavigationDelegate: With error code STATE_ERROR.VALIDATION_ERROR.50 for id 183c8e2d-b71c-44e8-b66a-8dac1571cc94

**Comment by Viswanth92** [comment]
Same issue here. Only started today:

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/YoutubePlayer_in_WKWebView.framework/YoutubePlayer_in_WKWebView: initWithFrame:configuration:, isMainFrame, setNavigationDelegate:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Best regards,

The App Store Team

**Comment by ygag-badusha** [comment]
Same issue from today

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/YoutubePlayer_in_WKWebView.framework/YoutubePlayer_in_WKWebView: initWithFrame:configuration:, isMainFrame, setNavigationDelegate:, targetFrame. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by abanoub-ashraf** [comment]
same issue here, only started hours ago

**Comment by GustavoAlvarez** [comment]
I tried again, and the upload was fine, guess it was just yesterday.
I Will reopen if the problem returns.
